routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::any('/test', 'TestController');

Route::group([ /*'middleware' => [ 'web' ], /* */ 'as' => 'ajax.', 'prefix' => '/ajax'], function () {
    Route::resource('machine', 'AjaxMachineController');
    Route::any('machine/{machine}/history', 'AjaxMachineController@history');

    Route::any('machine/{machine}/photo', 'AjaxMachineController@photo');
    Route::any('machine/{machine}/statistic', 'StatisticController');

    Route::any('machine/data/{uuid}', 'AjaxMachineController@postData');
});

Route::any('{all}', function () {
    return view('welcome');
})->where('all', '.*');

app/Models/Machine.php
<?php

namespace App\Models;

use App\Models\HistoryMachine;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Models\Machine
 *
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine newQuery()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Machine onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine query()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Machine withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Machine withoutTrashed()
 * @mixin \Eloquent
 * @property int $id
 * @property string|null $deleted_at
 * @property string $name
 * @property string $description
 * @property string $connect
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\HistoryMachine[] $histories
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereConnect($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereUpdatedAt($value)
 * @property int $empty_weight
 * @property int $full_weight
 * @property string $location
 * @property string $type
 * @property string $uuid
 * @property int $volume
 * @property-read array $statday_week
 * @property-read \App\Models\HistoryMachine $lasthist
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Statday[] $statday
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereEmptyWeight($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereFullWeight($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereLocation($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereUuid($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Machine whereVolume($value)
 */
class Machine extends Model
{
    use SoftDeletes;

    protected $table = 'machines';

    protected $fillable = [
        'name',
        'description',
        'connect',
        'location',
        'type',
        'volume',
        'empty_weight',
        'full_weight',
    ];

    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'description' => 'string',
        'connect' => 'string',
        'location'=> 'string',
        'uuid'=> 'string',
        'type'=> 'string',
        'volume'=> 'integer',
        'empty_weight'=> 'integer',
        'full_weight'=> 'integer',
    ];

    public function histories()
    {
        return $this->hasMany(HistoryMachine::class, 'machine_id', 'id');
    }

    public function lasthist()
    {
        return $this->hasOne(HistoryMachine::class, 'machine_id', 'id')->orderBy('created_at', 'desc');
    }

    public function statday()
    {
        $query = $this->hasMany(Statday::class, 'machine_id', 'id');

        $timeStart = date('H') * 60 + date('i');
        $query->getBaseQuery()->select([
            'machine_id',
            \DB::raw('WEEKDAY(created_at) AS dayofweek'),

            \DB::raw("DATE_FORMAT(DATE_ADD('2000-01-01', INTERVAL (DATE_FORMAT(created_at,'%H') * 60 + (DATE_FORMAT(created_at,'%i') DIV 5 * 5)) MINUTE), '%H:%i' ) AS `time`"),
            \DB::raw("(DATE_FORMAT(created_at,'%H') * 60 + (DATE_FORMAT(created_at,'%i') DIV 5 * 5)) AS h"),
            \DB::raw('AVG(result) AS r_avg'),
            \DB::raw('SUM(result) AS r_sum'),
            \DB::raw('COUNT(result) AS r_count'),
        ])
            ->groupBy(['machine_id', 'dayofweek', 'h', 'time'])
            ->orderBy('h')
            ->having(\DB::raw('`dayofweek`'), '=', date('w'))
            ->having(\DB::raw('`h`'), '>=', $timeStart)
            ->having(\DB::raw('`h`'), '<=', $timeStart + 60)
        ;

        return $query;
    }

    /**
     * @return array
     */
    public function getStatdayWeekAttribute()
    {
        $dayofweek = date('w');
        $default = collect();
        for ($i = 0; $i < 1440; $i+=5) {
            $item = [
                "h" => $i,
                "dayofweek" => $dayofweek,
                "r_avg" => 0,
                "r_sum" => 0,
                "r_count" => 0,
                "time"=> \Carbon\Carbon::createFromFormat('U', $i * 60)->format('H:i'),
            ];
            $default[(string) $i] = $item;
        }

        collect($this->getRelationValue('statday'))->map(function ($v) use ($default) {
            $default[$v->h] = $v;
            return $v;
        })->keyBy('h');

        return $default->map(function ($v) {
            return [
                'time' => $v['time'],
                'avg' => $v['r_avg'],
            ];
        })->values();
    }
}

resources/views/example/machine/edit.blade.php
<?php
/** @var \App\Models\Machine $model */
?>
@extends('example.layout')

@section('content')

    <form method="post" action="{{ $model->id ? route('ajax.machine.update') : route('ajax.machine.update', ['machine' => $model->id])}}">
        @if($model->id) @method('PUT')
        @else @method('POST')
        @endif

        @csrf

        <h1>Machine</h1>
        <div class="form-group row">
            <label for="staticName" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" required id="staticName" name="name" value="{{$model->name}}">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputDescription" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" required id="inputDescription" name="description" value="{{$model->description}}">
            </div>
        </div>

        <div class="form-group row">
            <label for="inputUrl" class="col-sm-2 col-form-label">Url</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" required id="inputUrl" name="connect" value="{{$model->connect}}">
            </div>
        </div>

            <div class="form-group row">
                <label for="inputLocation" class="col-sm-2 col-form-label">location</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" required id="inputLocation" name="location" value="{{$model->location}}">
                </div>
            </div>

            <div class="form-group row">
                <label for="inputType" class="col-sm-2 col-form-label">Type</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" required id="inputType" name="type" value="{{ $model->type ?? 'machine'}}">
                </div>
            </div>

            <div class="form-group row">
                <label for="inputVolume" class="col-sm-2 col-form-label">Volume</label>
                <div class="col-sm-10">
                    <input type="number" min="0" step="1" class="form-control" required id="inputVolume" name="volume" value="{{$model->volume}}">
                </div>
            </div>

            <div class="form-group row">
                <label for="input_empty_weight" class="col-sm-2 col-form-label">empty_weight</label>
                <div class="col-sm-10">
                    <input type="number" min="0" step="1" class="form-control" required id="input_empty_weight" name="empty_weight" value="{{$model->empty_weight}}">
                </div>
            </div>

            <div class="form-group row">
                <label for="input_full_weight" class="col-sm-2 col-form-label">full_weight</label>
                <div class="col-sm-10">
                    <input type="number" min="0" step="1" class="form-control" required id="input_full_weight" name="full_weight" value="{{$model->full_weight}}">
                </div>
            </div>

        <button type="submit" class="btn btn-primary my-1">Submit</button>
    </form>

@endsection